flow:
  target: videotuna.flow.stepvideo.StepVideoModelFlow
  params:
    ckpt_path: checkpoints/stepvideo/stepvideo-t2v
    denoiser_ckpt_path: ${flow.params.ckpt_path}/transformer
    scheduler_ckpt_path: ${flow.params.ckpt_path}/scheduler
    first_stage_ckpt_path: ${flow.params.ckpt_path}/vae
    cond_stage_ckpt_path: ${flow.params.ckpt_path}/step_llm
    cond_stage_2_ckpt_path: ${flow.params.ckpt_path}/hunyuan_clip
    enable_model_cpu_offload: True
    enable_sequential_cpu_offload: False

    scheduler_config: 
      target: videotuna.models.stepvideo.stepvideo.diffusion.scheduler.FlowMatchDiscreteScheduler
      use_from_pretrained: True
      params:
        pretrained_model_name_or_path: ${flow.params.scheduler_ckpt_path}

    denoiser_config:
      target: videotuna.models.stepvideo.stepvideo.modules.model.StepVideoModel
      use_from_pretrained: True
      params:
        pretrained_model_name_or_path: ${flow.params.denoiser_ckpt_path}
        torch_dtype: ${dtype_resolver:torch.bfloat16}
        attention_type: torch

    first_stage_config:
      target: videotuna.models.stepvideo.stepvideo.vae.vae.AutoencoderKL
      params:
        z_channels: 64
        model_path: ${flow.params.first_stage_ckpt_path}/vae_v2.safetensors
        version: 2

    cond_stage_config:
      target: videotuna.models.stepvideo.stepvideo.text_encoder.stepllm.STEP1TextEncoder
      params:
        model_dir: ${flow.params.cond_stage_ckpt_path}
        max_length: 320

    cond_stage_2_config:
      target: videotuna.models.stepvideo.stepvideo.text_encoder.clip.HunyuanClip
      params:
        model_dir: ${flow.params.cond_stage_2_ckpt_path}
        max_length: 77

inference:
  ckpt_path: checkpoints/stepvideo/stepvideo-t2v
  mode: t2v
  savedir: results/t2v/stepvideo
  seed: 42
  height: 544
  width: 992
  frames: 51 
  num_inference_steps: 50
  time_shift: 13.0
  unconditional_guidance_scale: 12.0
  prompt_file: '一名宇航员在月球上发现一块石碑，上面印有“stepfun”字样，闪闪发光'
  uncond_prompt: ''
  pos_prompt: ''
  n_samples_prompt: 1
  bs: 1
  savefps: 28
  enable_model_cpu_offload: True
  enable_sequential_cpu_offload: False

  mapping:
    inference.ckpt_path : flow.params.ckpt_path
    inference.enable_model_cpu_offload: flow.params.enable_model_cpu_offload
    inference.enable_sequential_cpu_offload: flow.params.enable_sequential_cpu_offload