flow:
  target: videotuna.flow.stepvideo.StepVideoModelFlow
  params:
    ckpt_path: /project/llmsvgen/songsong/DiffSynth-Studio/models/stepfun-ai/stepvideo-t2v
    denoiser_ckpt_path: ${flow.params.ckpt_path}/transformer
    scheduler_ckpt_path: ${flow.params.ckpt_path}/scheduler
    first_stage_ckpt_path: ${flow.params.ckpt_path}/vae
    cond_stage_ckpt_path: ${flow.params.ckpt_path}/step_llm
    cond_stage_2_ckpt_path: ${flow.params.ckpt_path}/hunyuan_clip

    scheduler_config: 
      target: videotuna.stepvideo.stepvideo.diffusion.scheduler.FlowMatchDiscreteScheduler
      use_from_pretrained: True
      params:
        pretrained_model_name_or_path: ${flow.params.scheduler_ckpt_path}

    denoiser_config:
      target: videotuna.stepvideo.stepvideo.modules.model.StepVideoModel
      use_from_pretrained: True
      params:
        pretrained_model_name_or_path: ${flow.params.denoiser_ckpt_path}
        torch_dtype: ${dtype_resolver:torch.bfloat16}

    first_stage_config:
      target: videotuna.stepvideo.stepvideo.vae.vae.AutoencoderKL
      params:
        z_channels: 64
        model_path: ${flow.params.first_stage_ckpt_path}/vae_v2.safetensors
        version: 2

    cond_stage_config:
      target: videotuna.stepvideo.stepvideo.text_encoder.stepllm.STEP1TextEncoder
      params:
        model_dir: ${flow.params.cond_stage_ckpt_path}
        max_length: 320

    cond_stage_2_config:
      target: videotuna.stepvideo.stepvideo.text_encoder.clip.HunyuanClip
      params:
        model_dir: ${flow.params.cond_stage_2_ckpt_path}
        max_length: 77

inference:
  ckpt_path: /project/llmsvgen/songsong/DiffSynth-Studio/models/stepfun-ai/stepvideo-t2v
  mode: t2v
  savedir: results/t2v/videocrafter2
  seed: 42
  height: 544
  width: 992
  num_frames: 204 
  num_inference_steps: 5
  n_samples_prompt: 1
  time_shift: 13.0
  bs: 1
  ddim_steps: 1
  ddim_eta: 1.0
  unconditional_guidance_scale: 12.0
  fps: 1
  prompts: '一名宇航员在月球上发现一块石碑，上面印有“stepfun”字样，闪闪发光'

  neg_magic: ''
  pos_magic: ''