flow:
  target: videotuna.flow.hunyuanvideo.HunyuanVideoFlow
  params:
    # Model Configuration
    precision: bf16
    rope_theta: 256
    time_shift: 7.0

    # Image-to-Video Settings
    i2v_mode: true
    i2v_condition_type: token_replace
    use_cpu_offload: true
    disable_autocast: false

    # VAE Configuration
    vae_type: 884-16c-hy
    vae_precision: fp16
    vae_tiling: true

    # Path Settings
    ckpt_path: checkpoints/hunyuanvideo/HunyuanVideo-I2V
    denoiser_ckpt_path: ${flow.params.ckpt_path}
    dit_weight: ${flow.params.ckpt_path}/hunyuan-video-i2v-720p/transformers/mp_rank_00_model_states.pt
    first_stage_ckpt_path: ${flow.params.ckpt_path}/hunyuan-video-i2v-720p/vae

    # Undeveloppred Settings
    use_fp8: false
    ulysses_degree: 1
    ring_degree: 1

    use_lora: false
    lora_path: ''
    lora_scale: 1.0
    lora_rank: 64
      
    first_stage_config:
      target: videotuna.models.hunyuan.hyvideo_i2v.vae.autoencoder_kl_causal_3d.AutoencoderKLCausal3DWrapper
      params:
        vae_type: ${flow.params.vae_type}
        vae_path: ${flow.params.first_stage_ckpt_path}
        use_cpu_offload: ${flow.params.use_cpu_offload}
        vae_precision: fp16
        device: cuda
    
    cond_stage_config:
      target: videotuna.models.hunyuan.hyvideo_i2v.text_encoder.TextEncoderWrapper
      params:
        i2v_mode: ${flow.params.i2v_mode}
        i2v_condition_type: ${flow.params.i2v_condition_type}
        text_encoder: "llm-i2v"
        text_states_dim: 4096
        text_len: 256
        tokenizer: llm-i2v
        prompt_template: dit-llm-encode-i2v
        prompt_template_video: dit-llm-encode-video-i2v
        hidden_state_skip_layer: 2
        apply_final_norm: false
        reproduce: false
        use_cpu_offload: ${flow.params.use_cpu_offload}
        device: cuda
        text_encoder_precision: "fp16"

    cond_stage_2_config:
      target: videotuna.models.hunyuan.hyvideo_i2v.text_encoder.TextEncoder
      params:
        text_encoder_type: clipL
        max_length: 77
        text_encoder_precision: fp16
        tokenizer_type: clipL
        device: cpu
    
    # Denoiser model wrapper 
    denoiser_config:
      target: videotuna.models.hunyuan.hyvideo_i2v.modules.models.HYVideoDiffusionTransformerWrapper
      params:
        i2v_mode: ${flow.params.i2v_mode}
        i2v_condition_type: ${flow.params.i2v_condition_type}
        device: 'cuda'
        precision: bf16
        latent_channels: 16
        text_states_dim: 4096
        text_states_dim_2: 768
        gradient_checkpoint: false
        gradient_checkpoint_layers: -1
        embedded_cfg_scale: 6.0
        model: HYVideo-T/2
        ckpt_path: ${flow.params.denoiser_ckpt_path}
        i2v_dit_weight: ${flow.params.dit_weight}
        load_key: module
    
    # Diffusion sampling scheduler
    scheduler_config:
      target: videotuna.models.hunyuan.hyvideo_i2v.diffusion.schedulers.scheduling_flow_match_discrete.FlowMatchDiscreteScheduler
      params:
        shift: ${flow.params.time_shift}
        reverse: True
        solver: 'euler'



inference:
  mode: i2v
  ckpt_path: checkpoints/hunyuanvideo/HunyuanVideo-I2V
  dit_weight: checkpoints/hunyuanvideo/HunyuanVideo-I2V/hunyuan-video-i2v-720p/transformers/mp_rank_00_model_states.pt
  savedir: results/i2v/hunyuanvideo
  seed: 42
  height: 360
  width: 640
  i2v_resolution: 360p
  # height: 720
  # width: 1280
  # i2v_resolution: 720p
  prompt_dir: "inputs/i2v/576x1024"      
  num_inference_steps: 50                
  time_shift: 7.0                
  unconditional_guidance_scale: 1.0  
  uncond_prompt: null                     
  frames: 129
  n_samples_prompt: 1
  bs: 1
  savefps: 28
  embedded_guidance_scale: 6.0
  ulysses_degree: 1
  ring_degree: 1
  xdit_adaptive_size: false

  i2v_mode: true
  i2v_condition_type: token_replace
  i2v_stability: true
  enable_sequential_cpu_offload: true
  enable_vae_tiling: true

  mapping:
    inference.time_shift : flow.params.time_shift
    inference.i2v_mode : flow.params.i2v_mode
    inference.i2v_condition_type : flow.params.i2v_condition_type
    inference.ring_degree : flow.params.ring_degree
    inference.ulysses_degree : flow.params.ulysses_degree
    inference.ckpt_path : flow.params.ckpt_path
    inference.dit_weight : flow.params.dit_weight
    inference.enable_sequential_cpu_offload : flow.params.use_cpu_offload
    inference.enable_vae_tiling: flow.params.vae_tiling


    

