model:
  base_learning_rate: 6.0e-06 # 1.5e-04
  scale_lr: False
  # empty_params_only: True # disable this means finetuning all parameters
  # sd_checkpoint: /project/llmsvgen/share/shared_ckpts/StableDiffusion/v2-1_512-ema-pruned.ckpt
  # pretrained_checkpoint: /project/llmsvgen/share/shared_ckpts/VideoCrafter/VideoCrafter2-Text2Video-512/model.ckpt
  target: src.lvdm.models.iddpm3d.LatentDiffusion
  params:
    # loss_type: l1
    log_every_t: 200
    linear_start: 0.00085
    linear_end: 0.012
    num_timesteps_cond: 1
    timesteps: 1000
    first_stage_key: video
    cond_stage_key: caption
    # cond_stage_trainable: false
    cond_stage_trainable: true
    conditioning_key: crossattn_stdit
    image_size: # TO CHECK 
    - 32
    - 32
    channels: 4
    scale_by_std: false
    scale_factor: 0.18215
    use_ema: false
    uncond_type: empty_seq
    monitor: val/loss_simple_ema
    encoder_type: 2d
    use_scale: true
    scale_b: 0.7 # adapt to videocrafter-v2

    unet_config:
      target: src.opensora.models.stdit.stdit.STDiT_XL_2
      params:
        # from_pretrained: None
        # qk_norm: True
        # enable_flash_attn: True
        # enable_flashattn: True
        # enable_layernorm_kernel: True
        # # freeze_y_embedder: True
        # freeze: 'text'
        space_scale: 0.5
        time_scale: 1.0
        # from_pretrained: "PixArt-XL-2-512x512.pth"
        enable_flashattn: True
        enable_layernorm_kernel: False
        input_size:
        - 16
        - 32
        - 32 
        # skip_y_embedder: True
        # freeze_previous_blocks: 
        # - True
        # - 'inter' 
    first_stage_config:
      target: src.lvdm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 512
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      # target: lvdm.modules.encoders.condition.FrozenOpenCLIPEmbedder
      target: src.opensora.models.text_encoder.t5.T5Encoder
      params:
        from_pretrained: "DeepFloyd/t5-v1_1-xxl"
        model_max_length: 120
        shardformer: False # TODO 

data:
  target: data.lightning_data.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 16
    wrap: false
    train:
      target: data.macvid.MaCVid
      params:
        data_root: configs/data/macvid/train_data.yaml
        resolution: [256, 256]
        video_length: 16
        subset_split: all
    validation:
      target: data.macvid.MaCVid
      params:
        data_root: configs/data/macvid/val_data.yaml
        resolution: [256, 256]
        video_length: 16
        subset_split: all

lightning:
  callbacks:
    image_logger:
      target: utils.callbacks.ImageLogger
      params:
        batch_frequency: 20
        max_images: 6
        to_local: True # save videos into files
        log_images_kwargs:
          unconditional_guidance_scale: 12 # need this, otherwise it is grey
        save_dir: ./results
    metrics_over_trainsteps_checkpoint:
      target: pytorch_lightning.callbacks.ModelCheckpoint
      params:
        filename: "{epoch:06}-{step:09}"
        save_weights_only: False
        every_n_epochs: 300
        every_n_train_steps: null
  trainer:
    benchmark: True
    batch_size: 1
    num_workers: 38
    num_nodes: 1
    accumulate_grad_batches: 2
    max_epochs: 2000
    precision: bf16 # training precision
  modelcheckpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      every_n_epochs: 1
      filename: "{epoch:04}-{step:06}"