flow:
  target: videotuna.flow.wanvideo.WanVideoModelFlow
  params:
    task: "i2v-14B"                   # The task to run (choices from WAN_CONFIGS.keys())
    ckpt_path: "checkpoints/wan/Wan2.1-I2V-14B-720P"                    # The path to the checkpoint directory.
    offload_model: true               # Whether to offload the model to CPU after each model forward.
    ulysses_size: 1                   # The size of the ulysses parallelism in DiT.
    ring_size: 1                      # The size of the ring attention parallelism in DiT.
    t5_fsdp: false                    # Whether to use FSDP for T5.
    t5_cpu: false                     # Whether to place T5 model on CPU.
    dit_fsdp: false                   # Whether to use FSDP for DiT.
    use_prompt_extend: false          # Whether to use prompt extend.
    prompt_extend_method: "local_qwen" # The prompt extend method to use (choices: dashscope, local_qwen)
    prompt_extend_model: null         # The prompt extend model to use.
    prompt_extend_target_lang: "zh"   # The target language of prompt extend (choices: zh, en)
    seed: 42                     # The seed to use for generating the image or video


    scheduler_config: __is_first_stage__

    denoiser_config:
      target: videotuna.wan.wan.modules.model.WanModel
      use_from_pretrained: true
      params:
        pretrained_model_name_or_path: ${flow.params.ckpt_path}

    first_stage_config:
      target: videotuna.wan.wan.modules.vae.WanVAE_
      params:
        dim: 96
        z_dim: 16
        dim_mult: [1, 2, 4, 4]
        num_res_blocks: 2
        attn_scales: []
        temperal_downsample: [false, true, true]
        dropout: 0.0

    cond_stage_config:
      target: videotuna.wan.wan.modules.t5.T5Encoder
      params:
        dim: 4096
        dim_attn: 4096
        dim_ffn: 10240
        num_heads: 64
        num_buckets: 32
        shared_pos: false
        dropout: 0.1
        vocab: 256384
        num_layers: 24

      
    cond_stage_2_config:
      target: videotuna.wan.wan.modules.clip.XLMRobertaCLIP
      params:
        embed_dim: 1024
        image_size: 224
        patch_size: 14
        vision_dim: 1280
        vision_mlp_ratio: 4
        vision_heads: 16
        vision_layers: 32
        vision_pool: "token"
        activation: "gelu"
        vocab_size: 250002
        max_text_len: 514
        type_size: 1
        pad_id: 1
        text_dim: 1024
        text_heads: 16
        text_layers: 24
        text_post_norm: true
        text_dropout: 0.1
        attn_dropout: 0.0
        proj_dropout: 0.0
        embedding_dropout: 0.0

inference:
  mode: i2v
  ckpt_path: "checkpoints/wan/Wan2.1-I2V-14B-720P"
  prompt_dir: "inputs/i2v/576x1024"
  savedir: results/i2v/wanvideo
  seed: 42
  height: 720
  width: 1280
  solver: "unipc"           
  num_inference_steps: 40                
  time_shift: 5.0                
  unconditional_guidance_scale: 5.0                       
  frames: 81
  n_samples_prompt: 1
  bs: 1
  savefps: 16

  mapping:
    inference.ckpt_path : flow.params.ckpt_path
    inference.seed : flow.params.seed